Repository TreinaDev/pagamentos-td08-time01, pull requests merged in 2022-06, with the labels that each got.

#9 Feat/standardized implementation
  .github/pull_request_template.md
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/permissions_policy.rb
  config/puma.rb
  config/routes.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/system/visitor_visit_homepage_spec.rb
Labels: enhancement

#7 Feat/access app
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/admin.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/initializers/locale.rb
  config/locales/devise.en.yml
  config/locales/models/admin.pt-BR.yml
  config/locales/models/devise_admin.pt_BR.yml
  config/locales/pt-BR.yml
  config/routes.rb
  db/migrate/20220608235329_devise_create_admins.rb
  db/schema.rb
  spec/factories/admins.rb
  spec/models/admin_spec.rb
  spec/rails_helper.rb
  spec/support/devise_methods.rb
  spec/system/admin/admin_access_app_spec.rb
Labels: enhancement

#10 feat: Cria e lista categorias de clientes
  .ruby-version
  app/controllers/client_categories_controller.rb
  app/models/client_category.rb
  app/views/client_categories/index.html.erb
  app/views/client_categories/new.html.erb
  app/views/layouts/application.html.erb
  config/locales/models/client_categories.pt-BR.yml
  config/routes.rb
  db/migrate/20220609200027_create_client_categories.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/client_categories.rb
  spec/models/client_category_spec.rb
  spec/system/client_category/admin_registers_client_category_spec.rb
  spec/system/client_category/admin_views_client_category_spec.rb
Labels: enhancement

#29 Feat/adicionar gem faker
  Gemfile
  Gemfile.lock
  spec/factories/admins.rb
  spec/factories/client_categories.rb
Labels: enhancement

#21 Feat/exchange rate
  app/assets/stylesheets/custom.css
  app/controllers/client_categories_controller.rb
  app/controllers/exchange_rates_controller.rb
  app/models/client_category.rb
  app/models/exchange_rate.rb
  app/views/exchange_rates/index.html.erb
  app/views/exchange_rates/new.html.erb
  app/views/layouts/application.html.erb
  config/locales/models/exchange_rate_pt-BR.yml
  config/routes.rb
  db/migrate/20220613170840_create_exchange_rate.rb
  db/schema.rb
  spec/factories/exchange_rates.rb
  spec/models/client_category_spec.rb
  spec/models/exchange_rate_spec.rb
  spec/system/admin/admin_register_new_exchange_rate_spec.rb
  spec/system/client_category/admin_registers_client_category_spec.rb
  spec/system/client_category/admin_views_client_category_spec.rb
  spec/system/visitor_sees_exchange_rate_spec.rb
Labels: enhancement

#22 feat: Permite cadastro de cliente via API
  app/controllers/api/v1/client_people_controller.rb
  app/models/client_person.rb
  config/locales/models/client_people.pt-BR.yml
  config/routes.rb
  db/migrate/20220611172750_create_client_people.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/client_people.rb
  spec/models/client_person_spec.rb
  spec/requests/api/client_person/api_register_client_person_spec.rb
Labels: enhancement

#12 Feat/client
  app/models/client.rb
  config/locales/models/client.pt-BR.yml
  db/migrate/20220610164938_create_clients.rb
  db/migrate/20220610210402_change_client_type_in_client.rb
  spec/factories/clients.rb
  spec/models/client_spec.rb
Labels: enhancement

#18 Adiciona botão de cadastro para categoria de cliente
  app/assets/stylesheets/custom.css
  app/controllers/client_categories_controller.rb
  app/views/client_categories/index.html.erb
  app/views/client_categories/new.html.erb
  spec/system/client_category/admin_registers_client_category_spec.rb
  spec/system/client_category/admin_views_client_category_spec.rb
Labels: enhancement

#27 Feat/exchange rate review
  app/assets/stylesheets/custom.css
  app/controllers/exchange_rates_controller.rb
  app/models/admin.rb
  app/models/client.rb
  app/models/exchange_rate.rb
  app/views/exchange_rates/index.html.erb
  app/views/exchange_rates/new.html.erb
  app/views/exchange_rates/show.html.erb
  config/locales/models/exchange_rate_pt-BR.yml
  config/routes.rb
  db/migrate/20220613200145_add_columns_to_exchange_rate.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/clients.rb
  spec/factories/exchange_rates.rb
  spec/models/client_spec.rb
  spec/models/exchange_rate_spec.rb
  spec/requests/admin_approve_exchange_rate_request_spec.rb
  spec/requests/admin_recused_exchange_rate_request_spec.rb
  spec/system/exchange_rate/admin_approve_exchange_rate_spec.rb
  spec/system/exchange_rate/admin_recuse_exchange_rate_spec.rb
  spec/system/exchange_rate/admin_register_new_exchange_rate_spec.rb
  spec/system/exchange_rate/admin_sees_exchange_rate_details_spec.rb
  spec/system/visitor_sees_exchange_rate_spec.rb
Labels: enhancement

#17 Restrição de acesso no client_category
  app/controllers/client_categories_controller.rb
  app/views/layouts/application.html.erb
  spec/system/client_category/admin_registers_client_category_spec.rb
  spec/system/client_category/admin_views_client_category_spec.rb
Labels: enhancement

#25 Permitir ativação de Administrador
  Gemfile
  Gemfile.lock
  app/controllers/admin_permissions_controller.rb
  app/controllers/pendencies_controller.rb
  app/models/admin.rb
  app/models/admin_permission.rb
  app/models/application_record.rb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/pendencies/index.erb
  config/locales/models/admin.pt-BR.yml
  config/routes.rb
  db/migrate/20220610234210_add_status_to_admin.rb
  db/migrate/20220612131739_create_admin_permissions.rb
  db/migrate/20220612162631_add_active_admin_to_admin_permission.rb
  db/migrate/20220614023802_change_column_cpf.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/admins.rb
  spec/models/admin_spec.rb
  spec/models/client_category_spec.rb
  spec/models/exchange_rate_spec.rb
  spec/requests/admin_spec.rb
  spec/system/admin/admin_access_app_spec.rb
  spec/system/admin/admin_activate_a_pending_account_spec.rb
  spec/system/client_category/admin_registers_client_category_spec.rb
  spec/system/client_category/admin_views_client_category_spec.rb
Labels: enhancement

#35 Adicionar shoulda matchers
  Gemfile
  Gemfile.lock
  spec/models/admin_spec.rb
  spec/models/client_category_spec.rb
  spec/models/client_company_spec.rb
  spec/models/client_person_spec.rb
  spec/models/client_spec.rb
  spec/models/exchange_rate_spec.rb
  spec/support/shoulda_mathers.rb
Labels: enhancement

#32 Criar associações do cliente
  app/controllers/api/v1/client_companies_controller.rb
  app/controllers/api/v1/client_people_controller.rb
  app/models/client.rb
  app/models/client_category.rb
  app/models/client_company.rb
  app/models/client_person.rb
  db/migrate/20220614195141_add_client_category_to_client.rb
  db/migrate/20220614200738_add_client_to_client_person.rb
  db/migrate/20220614203808_add_client_to_client_company.rb
  db/schema.rb
  db/seeds.rb
  migrate
  spec/models/client_company_spec.rb
  spec/models/client_person_spec.rb
  spec/models/client_spec.rb
  spec/requests/api/client_company/api_register_client_company_spec.rb
  spec/requests/api/client_person/api_register_client_person_spec.rb
Labels: enhancement

#39 Funcionalidade: Cadastro de promoção
  app/controllers/promotions_controller.rb
  app/models/client_category.rb
  app/models/promotion.rb
  app/views/layouts/application.html.erb
  app/views/promotions/index.html.erb
  app/views/promotions/new.html.erb
  config/locales/models/promotion.pt-BR.yml
  config/routes.rb
  db/migrate/20220614202334_create_promotions.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/promotions.rb
  spec/models/promotion_spec.rb
  spec/system/promotion/admin_register_new_promotion_spec.rb
  spec/system/promotion/admin_sees_promotions_spec.rb
Labels: enhancement

#46 Corrigir restrição de acesso do admin pendente
  app/controllers/admin_permissions_controller.rb
  app/controllers/application_controller.rb
  app/controllers/pendencies_controller.rb
  db/seeds.rb
  spec/requests/admin_spec.rb
  spec/system/admin/admin_access_app_spec.rb
  spec/system/admin/admin_activate_a_pending_account_spec.rb
Labels: enhancement

#47 fix: bug de login com admin ativo
  app/controllers/application_controller.rb
  spec/system/admin/admin_access_app_spec.rb
Labels: bug

#42 Cadastro de cliente API
  .rubocop.yml
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/client_companies_controller.rb
  app/controllers/api/v1/client_people_controller.rb
  app/controllers/api/v1/clients_controller.rb
  app/controllers/concerns/.keep
  app/controllers/concerns/exception_handler.rb
  app/models/client.rb
  config/locales/models/client.pt-BR.yml
  config/routes.rb
  db/seeds.rb
  spec/requests/api/v1/client/api_register_client_spec.rb
  spec/requests/api/v1/client_company/api_register_client_company_spec.rb
  spec/requests/api/v1/client_person/api_register_client_person_spec.rb
Labels: enhancement

#40 Criar limite de crédito
  app/controllers/transaction_settings_controller.rb
  app/models/transaction_setting.rb
  app/views/layouts/application.html.erb
  app/views/transaction_settings/edit.html.erb
  app/views/transaction_settings/new.html.erb
  app/views/transaction_settings/shared/_form.html.erb
  config/locales/models/transaction_settings.pt-BR.yml
  config/routes.rb
  db/migrate/20220615124233_create_transaction_settings.rb
  db/schema.rb
  spec/factories/transaction_settings.rb
  spec/models/transaction_setting_spec.rb
  spec/system/admin/admin_edit_max_credit_spec.rb
  spec/system/admin/admin_register_max_credit_spec.rb
Labels: enhancement

#51 feat: Adicionar gem better errors
  Gemfile
  Gemfile.lock
Labels: enhancement

#52 fix: Remover recursos não utilizados
  app/controllers/api/v1/client_companies_controller.rb
  app/controllers/api/v1/client_people_controller.rb
  config/routes.rb
  spec/requests/api/v1/client_company/api_register_client_company_spec.rb
  spec/requests/api/v1/client_person/api_register_client_person_spec.rb
Labels: enhancement

#54 Feat/client balance
  Gemfile
  app/controllers/api/v1/clients_controller.rb
  app/models/client_company.rb
  app/models/client_person.rb
  config/routes.rb
  db/migrate/20220616015526_add_balance_to_client.rb
  db/schema.rb
  db/seeds.rb
  spec/models/client_company_spec.rb
  spec/models/client_person_spec.rb
  spec/requests/api/clients_data/api_expose_a_client_data_spec.rb
  spec/requests/api/v1/client/api_register_client_spec.rb
Labels: enhancement

#58 fix: better errors gem
  Gemfile
Labels: enhancement

#60 Adiciona Validações e Cria modelo ClientBalanceBonus
  app/controllers/api/v1/clients_controller.rb
  app/models/client.rb
  app/models/client_bonus_balance.rb
  app/models/client_category.rb
  app/models/client_company.rb
  app/models/client_person.rb
  config/locales/models/client_balance_bonus.pt-BR.yml
  db/migrate/20220620125151_create_client_balance_bonus.rb
  db/migrate/20220620135947_add_index_unique_to_tables.rb
  db/schema.rb
  spec/factories/client_balance_bonus.rb
  spec/factories/client_companies.rb
  spec/factories/client_people.rb
  spec/models/client_bonus_balance_spec.rb
  spec/models/client_category_spec.rb
  spec/models/client_company_spec.rb
  spec/models/client_person_spec.rb
  spec/system/promotion/admin_register_new_promotion_spec.rb
  spec/system/promotion/admin_sees_promotions_spec.rb
Labels: enhancement

#64 Feat/api exchange rate
  app/controllers/api/v1/exchange_rates_controller.rb
  config/routes.rb
  spec/requests/api/v1/clients_data/api_expose_a_client_data_spec.rb
  spec/requests/api/v1/exchange_rate/api_expose_exchange_rate_spec.rb
Labels: enhancement

#66 Transações de clientes
  .rubocop.yml
  app/controllers/api/v1/client_transactions_controller.rb
  app/controllers/client_transactions_controller.rb
  app/controllers/concerns/exception_handler.rb
  app/helpers/application_helper.rb
  app/models/client.rb
  app/models/client_transaction.rb
  app/services/cnpj_formatter.rb
  app/services/cpf_formatter.rb
  app/services/transaction_company.rb
  app/services/transaction_person.rb
  app/views/client_transactions/edit.html.erb
  app/views/client_transactions/index.html.erb
  app/views/layouts/application.html.erb
  config/application.rb
  config/initializers/locale.rb
  config/locales/models/api_models_errors.pt-BR.yml
  config/locales/models/client_people.pt-BR.yml
  config/locales/models/client_transaction.pt-BR.yml
  config/routes.rb
  db/migrate/20220620134617_create_client_transactions.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/client_categories.rb
  spec/factories/client_companies.rb
  spec/factories/client_people.rb
  spec/factories/client_transactions.rb
  spec/factories/clients.rb
  spec/models/client_category_spec.rb
  spec/models/client_transaction_spec.rb
  spec/requests/api/v1/client_transaction/register_new_transaction_spec.rb
  spec/system/client_transaction/admin_change_transaction_status_spec.rb
  spec/system/client_transaction/admin_visit_client_transaction_spec.rb
Labels: enhancement

#70 feat: Atualiza documentação
  README.md
  documentation.md
Labels: documentation

#74 Implementa layout base
  app/assets/config/manifest.js
  app/assets/stylesheets/custom.css
  app/assets/stylesheets/styles.css
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/javascript/application.js
  app/javascript/scripts.js
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard/_body.html.erb
  app/views/layouts/dashboard/_footer.html.erb
  app/views/layouts/dashboard/_navbar.html.erb
  app/views/layouts/dashboard/_top.html.erb
  app/views/transaction_settings/edit.html.erb
  app/views/transaction_settings/new.html.erb
  app/views/transaction_settings/shared/_form.html.erb
  config/credentials.yml.enc
  spec/system/admin/admin_access_app_spec.rb
  spec/system/admin/admin_activate_a_pending_account_spec.rb
  spec/system/visitor_sees_exchange_rate_spec.rb
Labels: enhancement

#72 Correções
  db/seeds.rb
  documentation/documentation.md
Labels: documentation

#77 Corrigir link da navbar
  Gemfile.lock
  app/views/layouts/dashboard/_top.html.erb
Labels: bug

#80 Adiciona listagem de clientes
  app/controllers/clients_controller.rb
  app/views/clients/index.html.erb
  app/views/layouts/dashboard/_navbar.html.erb
  config/routes.rb
  spec/system/client/admin_sees_client_list_spec.rb
Labels: enhancement

#84 fix: Correções no layout
  app/assets/images/ruby.png
  app/assets/stylesheets/custom.css
  app/controllers/clients_controller.rb
  app/views/client_categories/new.html.erb
  app/views/clients/index.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard/_body.html.erb
  app/views/layouts/dashboard/_footer.html.erb
  app/views/layouts/dashboard/_navbar.html.erb
  app/views/layouts/dashboard/_top.html.erb
  spec/system/client/admin_sees_client_list_spec.rb
Labels: bug

#76 Transações de clientes/02
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/client_transactions_controller.rb
  app/controllers/api/v1/clients_controller.rb
  app/controllers/client_transactions_controller.rb
  app/helpers/application_helper.rb
  app/javascript/application.js
  app/models/client.rb
  app/models/client_transaction.rb
  app/models/transaction_notification.rb
  app/services/check.rb
  app/services/client_transaction_service.rb
  app/services/set_bonus.rb
  app/services/set_error_type.rb
  app/services/summing_transaction.rb
  app/services/transaction_company.rb
  app/services/transaction_confirmation.rb
  app/services/transaction_person.rb
  app/views/client_transactions/edit.html.erb
  app/views/client_transactions/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/models/transaction_notification.pt-BR.yml
  db/migrate/20220624200708_create_transaction_notifications.rb
  db/migrate/20220625005110_add_code_to_client_transaction.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/transaction_notifications.rb
  spec/models/client_transaction_spec.rb
  spec/models/transaction_notification_spec.rb
  spec/requests/api/v1/client_transaction/register_new_transaction_spec.rb
  spec/requests/api/v1/clients_data/api_expose_a_client_data_spec.rb
  spec/requests/api/v1/exchange_rate/api_expose_exchange_rate_spec.rb
  spec/support/json/transaction_confirmation_code_not_found.json
  spec/support/json/transaction_confirmation_error_type_empty.json
  spec/support/json/transaction_confirmation_internal_server_error.json
  spec/support/json/transaction_confirmation_success.json
  spec/system/client_transaction/admin_change_transaction_status_spec.rb
  spec/system/client_transaction/admin_visit_client_transaction_spec.rb
  spec/system/promotion/admin_sees_promotions_spec.rb
Labels: enhancement

#86 Refatorações
  app/controllers/api/v1/clients_controller.rb
  app/services/set_bonus.rb
  spec/requests/api/v1/clients_data/api_expose_a_client_data_spec.rb
Labels: enhancement

#88 feat: Listar as transações
  app/controllers/client_transactions_controller.rb
  app/helpers/application_helper.rb
  app/views/client_transactions/index.html.erb
  config/locales/models/client_transaction.pt-BR.yml
  db/seeds.rb
  spec/system/client_transaction/admin_views_client_transactions_spec.rb
Labels: enhancement

#89 Refatoração
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/clients_controller.rb
  app/models/client_bonus_balance.rb
  app/serializers/client_company_serializer.rb
  app/serializers/client_person_serializer.rb
  app/serializers/client_transaction_serializer.rb
  app/services/cnpj_formatter.rb
  app/services/cpf_formatter.rb
  app/services/transaction_company.rb
  app/services/transaction_person.rb
  db/seeds.rb
  documentation/documentation.md
  spec/requests/api/v1/clients_data/api_expose_a_client_data_spec.rb
  spec/system/exchange_rate/admin_approve_exchange_rate_spec.rb
Labels: enhancement

#92 Feat/flow block
  app/controllers/api/v1/client_transactions_controller.rb
  app/services/check_exchange_rate_valid.rb
  spec/requests/api/v1/client_transaction/register_new_transaction_spec.rb
  spec/requests/api/v1/client_transaction/system_suspension_spec.rb
Labels: enhancement

#93 Feat/transactions
  .rubocop.yml
  app/controllers/client_transactions_controller.rb
  app/services/buy_products.rb
  app/services/buy_rubys.rb
  app/services/check.rb
  app/services/client_transaction_service.rb
  app/services/discounts.rb
  app/services/ecommerce_response_msg.rb
  app/services/set_error_type.rb
  app/services/transaction_company.rb
  app/services/transaction_confirmation.rb
  app/services/transaction_person.rb
  app/views/client_transactions/edit.html.erb
  config/locales/models/client_transaction.pt-BR.yml
  config/routes.rb
  spec/factories/client_balance_bonus.rb
  spec/rails_helper.rb
  spec/requests/api/v1/client_transaction/register_new_transaction_spec.rb
  spec/system/client_transaction/admin_updates_a_product_transaction_spec.rb
  spec/system/client_transaction/admin_updates_a_ruby_transaction_spec.rb
Labels: enhancement
